### ISSUE TITLE
File missing & Output parameter missing

### ISSUE THREAD

**Issue by Rradley** [EBI-Metagenomics/pipeline-v5#12]
[raw_read_single_Error.txt](https://github.com/EBI-Metagenomics/pipeline-v5/files/4812648/raw_read_single_Error.txt)
[Assembly_Error.txt](https://github.com/EBI-Metagenomics/pipeline-v5/files/4812649/Assembly_Error.txt)

These two shortened errors (full error messages available at request) occur when i run raw_reads single and assembly pipelines.

Any light on the issues would be a great help

**Comment by KateSakharova** [comment]
@Rradley I think I know what is wrong with assembly. Could you check path in **assembly.yml** in rfam_models of alpha_tmRNA.cm? Is it _/home/radleyrp/Documents/DELETE/ebi_pipeline/pipeline-v5/other/alpha_tmRNA.cm_ ?

Regarding another issue - it would be solved in a new release ~ in a week

**Comment by Rradley** [comment]
/home/radleyrp/Documents/DELETE/ebi_pipeline/pipeline-v5/other/alpha_tmRNA.cm : it is indeed. I noticed this folder and file do not exist.

That's amazing, thankyou!
