### ISSUE TITLE
Bug with chunking run_result_file_chunker.py

### ISSUE THREAD

**Issue by amkibriya** [EBI-Metagenomics/pipeline-v5#29]
Hi, 

The following line of code: 
`pipeline-v5/utils/result-file-chunker/run_result_file_chunker.py:78` --> ` tool_path = 'gt' `

Is causing a FileNotFoundError: ` FileNotFoundError: [Errno 2] No such file or directory: 'gt': 'gt' `

Can suggest a fix for it? 

Thanks in advance,
A

**Comment by amkibriya** [comment]
Is it some extra tool that we need to install? Could you also suggest which version, if yes?

Thanks in advance, 
Ashraf

**Comment by KateSakharova** [comment]
Hi @amkibriya,
thank you for repotring this! 

**gt** is genomeTools (The GenomeTools genome analysis system). It should be possible to install via pip https://pypi.org/project/genometools/. Do not forget to check do you have it in PATH or not after installation (```gt --help```)

We'll add this tool into new release version and documentation as well.

Kate
MGnify team

**Comment by amkibriya** [comment]
Hi Kate (@KeteSakharova), 

Thank you for your reply. 

I tried installing `gt` inside the docker image specified in `utils/result-file-chunker/result_chunker.cwl`. But it seems `gt` tries to create chunked files in the input file directory, which are then moved to the output `folder` directory by `utils/result-file-chunker/chunkFastaResultFileUtil.py` . But this generates the following error since the input directories are mounted readonly in the Docker by the cwltool ( this is also not caught by the cwltool and is reported as success):

```
INFO [job chinking_fasta_proteins] /data/tmp/cwlwork/6xils8fg$ docker \
    run \
    -i \
    --mount=type=bind,source=/data/tmp/cwlwork/6xils8fg,target=/HFLbvi \
    --mount=type=bind,source=/data/tmp/cwlwork/nbo02jiq,target=/tmp \
    --mount=type=bind,source=/data/tmp/cwlwork/qscyjxr3/ERR318583_1_FASTQ_CDS.faa,target=/var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa,readonly \
    --workdir=/HFLbvi \
    --read-only=true \
    --user=172863:1172863 \
    --rm \
    --env=TMPDIR=/tmp \
    --env=HOME=/HFLbvi \
    --cidfile=/data/tmp/cwlwork/x1a5u8zf/20201013082838-710623.cid \
    mgnify/pipeline-v5.python3 \
    run_result_file_chunker.py \
    -f \
    fasta \
    -i \
    /var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa \
    -o \
    folder \
    -t \
    p

Processing /var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa
/var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa  -  ERR318583_1_FASTQ_CDS.faa  -  1442  -  gt  -  folder
Running the FASTA file chunking tool with the following settings:
infile: /var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa
resultFileSuffix:ERR318583_1_FASTQ_CDS.faa
targetSize:1442
cutoff:1442.0MB
Checking for the '.chunks' file
Input file size in MB: 1852.2794666290283
Starting file chunking...
---> run fasta chunk
toolpath:  gt targetsize:  1442 path:  /var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa
--------error------
['gt', 'splitfasta', '-targetsize', '1442', '/var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa']
return code 1
b"fopen(): cannot open file '/var/lib/cwl/stg6a5ed76f-adef-4a49-9f34-a646cdaaa128/ERR318583_1_FASTQ_CDS.faa.1': Read-only file system\n"
File chunking finished.
Filtering for files with the following prefix: ERR318583_1_FASTQ_CDS.faa and the following format: prefix.[num]
out dir:folder
FASTA file chunking tool finished.
INFO [job chinking_fasta_proteins] Max memory used: 0MiB
INFO [job chinking_fasta_proteins] completed success
```

Perhaps, the `result_chunker.cwl` needs a `InitialWorkDirRequirement:` ? Or maybe a solution using `return_directory.cwl`?

Further, there is also a similar issue with `utils/move.cwl `, where the `mv` command fails since the file is mounted readonly.

Thanks for your help.

Regards, 
Ashraf

**Comment by KateSakharova** [comment]
Ashraf @amkibriya, what branch are you using for run?

**Comment by amkibriya** [comment]
> Ashraf @amkibriya, what branch are you using for run?

@KeteSakharova  We forked off our code from the develop branch. I haven't merged it with the latest changes pushed to develop or master, but I see the code is still the same in both develp and master. 

Maybe its easier if we can discuss it in detail over gitter?

**Comment by KateSakharova** [comment]
@amkibriya ok, I wrote you in gitter.
