### ISSUE TITLE
Refseq db

### ISSUE THREAD

**Issue by Mohamedema** [EBI-Metagenomics/pipeline-v5#35]
Please can I know the version of used SILVA database  (eg SILVA_138.1_SSURef_NR99.fasta.gz) also please, what is the source of uniref90_diamond-v0.9.21.dmnd.gz is this database generate from NCBI nr for diamond?

**Comment by KateSakharova** [comment]
@Mohamedema  hello, 
you can check all versions here https://emg-docs.readthedocs.io/en/latest/analysis.html#overview
If you have more questions we are happy to answer.

Kate
