### ISSUE TITLE
Running this pipeline

### ISSUE THREAD

**Issue by evilvenom** [EBI-Metagenomics/pipeline-v5#44]
How do I run this pipeline from my CLI?

**Comment by caballero** [comment]
Hi, the pipeline is implemented in [CWL](https://www.commonwl.org/user_guide/index.html), therefore you need to have installed an executor such as [cwltool](https://github.com/common-workflow-language/cwltool) or [toil](https://github.com/DataBiosphere/toil), then you can use the main [workflows](https://github.com/EBI-Metagenomics/pipeline-v5/tree/master/workflows) with a custom YAML file ([base configurations](https://github.com/EBI-Metagenomics/pipeline-v5/tree/master/workflows/ymls)).
However, as there are many dependencies and databases involved, installation and execution is not easy, it could be better to submit your data to [ENA](https://www.ebi.ac.uk/metagenomics/) and request the analysis.
