### ISSUE TITLE
Go Slim Banding IDs

### ISSUE THREAD

**Issue by ucabuk** [EBI-Metagenomics/pipeline-v5#47]
Hi,

I am trying to implement only GO-slim part in the pipeline. However, I am a bit confused about Go-Slim part. 

Should the `metagenomics_go_slim_banding.txt` and `metagenomics_go_slim_ids.txt` files, where is in the directory `tools/Go-Slim`, be updated ? If so, how could I update, based on what ? Or how could it be created new one ? I guess, It is input-specific, is not it or is it like should be manually created an annotation (.gaf) for your gene set of interest ? 

Thank you.
Best,
Ugur

**Comment by Vkale1** [comment]
Hi Ugur,
To mirror the results in v5 of the MGnify pipeline, you can use the existing banding, id and obo files in the tools/go-slim directory.

However if you wish to update the go-slim files you can find the downloads on the gene-ontology website here: http://release.geneontology.org/2022-03-22/ontology/subsets/index.html
You would need the goslim_metagenomics.obo and goslim_metagenomics.tsv files. The tsv file would need to be reformatted to match the current metagenomics_go_slim_banding.txt file. Additionally you can pull out the IDs only to generate the metagenomics_go_slim_ids.txt file. 

As long as the go_summary-config.json in the same tools/Go-Slim folder contains the paths to the updated files, the existing go_summary_pipeline-1.0.py script should then generate the required gaf file to produce the go-slim summary.

**Comment by ucabuk** [comment]
Hi,

Thank you very much ! Now It is more clear for me. Just an another quick question, Are Prokaryotes-related annotations more dominated in the metagenomics_go_slim_banding.txt file or can it be found eukaryota-related annotations as well ?

**Comment by Vkale1** [comment]
Hi Ugur, the banding.txt file contains terms that are specific to prokaryotes, specific to eukaryotes and non-specific, but unfortunately we don’t have a measure of the relative numbers of each.

**Comment by ucabuk** [comment]
Hi, thanks a lot ! Now, It is very informative for me. 
Best,
