### ISSUE TITLE
inferal issue 

### ISSUE THREAD

**Issue by Mohamedema** [EBI-Metagenomics/pipeline-v5#5]
Greeting
I used the model that you created against my metagenomic data to do my cmsearch, but I got a lot of ncRNA in my sample with each cmsearch model file, I expect my fill will lose a lot of sequence information after coordinate masking, I do not really know what should I do
If you can give me advice it will really help
Many thanks 
Kind regards

**Comment by rdfinn** [comment]
If you are getting a lot of matched to the cm models, you are likely to have a lot of ribosomal RNAs or tRNAs, as there are multiple related models. The following script decides which ones to take.  However, I do not follow why you are worried about the co-ordinate masking. If you have a lot of ncRNAs (to these models) then you are unlikely to have protein matches.
