### ISSUE TITLE
typo in awk-tool?

### ISSUE THREAD

**Issue by RZ9082** [EBI-Metagenomics/pipeline-v5#61]
Hey,

I am currently working on porting the amplicon workflow to galaxy.
Building the wrappers for the different tools I noticed in the pipeline-v5/tools/RNA_prediction/extract-coords/awk_tool there is a ‘q’ in line 9 `awk '{print $1"-"$3"/q"$8"-"$9" "$8" "$9" "$1}' ${INPUT} > ${NAME}".matched_seqs_with_coords"`
that actually does not appear in the expected output. Is that just a typo?

Best,
Rand

**Comment by mberacochea** [comment]
Hi @RZ9082,

Apologies for the delayed response; somehow, we missed your message.

@KeteSakharova, could you please assist @RZ9082?

By the way, we have plans to port this pipeline to Nextflow with upgrades and new features. Although I don't have an exact ETA, we expect it to be completed either later this year or early next year.

Cheers

**Comment by KateSakharova** [comment]
Hi @RZ9082, 
No, there is no typo there. Next step requires 'q' being in file. 

We have imported that part to Nextflow already. You can try it https://github.com/EBI-Metagenomics/motus_pipeline/blob/main/modules/easel.nf#L19

Kate
