### ISSUE TITLE
Missing input parameter

### ISSUE THREAD

**Issue by Rradley** [EBI-Metagenomics/pipeline-v5#9]
[Error.txt](https://github.com/EBI-Metagenomics/pipeline-v5/files/4758902/Error.txt)

After updating my cwltool to v1.2.0-dev2 and enabling via cwltool --enable-dev ...*

I ran into the attached error, If you are able to advise that would be great!

**Comment by KateSakharova** [comment]
@Rradley did you generate yml file with **create_yml.py**? Do you have lines: 
```bash
CGC_postfixes:
  - '_CDS.faa'
  - '_CDS.ffn'
``` 
in your yml file. They should be there for WGS and assembly analysis
https://github.com/EBI-Metagenomics/pipeline-v5/blob/rebuild_dockers/create_yml.py#L139

**Comment by Rradley** [comment]
For clarity, I am attempting to run the raw-reads pipeline with raw-reads.yml, using the folowing line, when I got the above error:
`$ cwltool workflows/conditionals/raw-reads-wf-single-v.5-cond.cwl raw-reads.yml`

I created the file with create _yml.py. To be on the safe side, I recreated all the files again using it. and inside the raw-reads.yml, I do not have
`CGC_postfixes:`
`- '_CDS.faa'`
`- '_CDS.ffn'`
in my file. I also noticed that when i run creat_yml.py with raw-reads, it makes the same file as amplicon, and tells me as such:
`$ python3 create_yml.py --dir ./ --type raw_reads'
'amplicon'
'---------> yml done`

**Comment by KateSakharova** [comment]
@Rradley yes, this is a bug in documentation, I'll fix it now. Thank you :)
you need to run 
```
python3 create_yml.py --dir ./ --type wgs
```

**Comment by Rradley** [comment]
Thank you for your quick reply!

With both the raw-reads single and assembly pipelines I get these errors:

`ERROR Workflow error, try again with --debug for more information:`
`Invalid job input record:`
`workflows/conditionals/raw-reads-wf-single-v.5-cond.cwl:28:5: Missing required input parameter 'other_ncrna_models'`

`ERROR Workflow error, try again with --debug for more information:`
`Invalid job input record:`
`workflows/conditionals/assembly-wf--v.5-cond.cwl:35:5: Missing required input parameter                                               'other_ncrna_models'`

**Comment by KateSakharova** [comment]
@Rradley sorry, we haven't completed testing for this branch, that is why you can bump into our typos. We strongly recommend to analyse data using our resources https://www.ebi.ac.uk/metagenomics/

Regarding your error: open your yml files and replace **other_ncRNA_models** with **other_ncrna_models**
